apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: backstage
  labels:
    app: backstage
spec:
  type: ClusterIP
  ports:
    - port: 7007
      targetPort: 7007
      protocol: TCP
      name: http
  selector:
    app: backstage
