apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |
    listener 1883

    # Allow anonymous connections for simplicity during initial setup
    # !!! IMPORTANT: For production, set this to 'false' and add users/passwords !!!
    allow_anonymous true

    # Enable persistence for retaining messages and device states
    persistence true
    persistence_location /mosquitto/data/

    # Log to stdout for Kubernetes logs
    log_dest stdout

    # Other common settings (optional)
    # connection_messages true
    # log_timestamp true
    # max_queued_messages 1000
    # message_size_limit 0 # No limit