apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    chart: gitea-charts
    repoURL: https://dl.gitea.com/charts/
    targetRevision: '1.16.1'
    helm:
      releaseName: gitea
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea