apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    chart: gitea-charts
    repoURL: gitea-charts/gitea
    helm:
      releaseName: gitea
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea