apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.3.0
    healm:
      valuesFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
  syncPolicy:
    automated:
      prune: true 