apiVersion: v1
kind: ConfigMap
metadata:
  name: automation-config
  namespace: home-automation
data:
  MQTT_BROKER_URL: "ws://mosquitto.mqtt.svc.cluster.local:9001"
  NODE_ENV: "production"
  LOG_LEVEL: "info"