apiVersion: v1
kind: Service
metadata:
  name: home-automation
  namespace: home-automation
spec:
  selector:
    app: home-automation
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP