apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: zigbee2mqtt
data:
  configuration.yaml: |
    homeassistant: true
    permit_join: false
    mqtt:
      base_topic: zigbee2mqtt
      server: 'mqtt://mosquitto.mqtt.svc.cluster.local:1883'
    serial:
      port: /dev/ttyUSB0
      adapter: zstack
    advanced:
      log_level: info
      pan_id: 10541
      ext_pan_id: [0x00, 0x12, 0x4b, 0x00, 0x2f, 0x8a, 0xed, 0x18]
      channel: 25
    frontend:
      port: 8080
    experimental:
      new_api: true
      transmit_power: 20
      touchlink: true
