apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      nodeSelector:
        zigbee-usb: "true"
      initContainers:
      - name: copy-config
        image: busybox:latest
        command: ["sh", "-c"]
        args:
        - |
          echo "Copying configuration.yaml from configmap to persistent volume..."
          cp /configmap/configuration.yaml /app/data/configuration.yaml
          if [ -f /configmap/devices.yaml ]; then
            echo "Copying devices.yaml from configmap to persistent volume..."
            cp /configmap/devices.yaml /app/data/devices.yaml
          fi
          echo "Configuration copied."
        volumeMounts:
        - name: config
          mountPath: /configmap
        - name: data
          mountPath: /app/data
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: zigbee-device
          mountPath: /dev/ttyUSB0
        - name: zigbee-dialout
          mountPath: /dev/serial
        - name: data
          mountPath: /app/data
      volumes:
      - name: zigbee-device
        hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
      - name: zigbee-dialout
        hostPath:
          path: /dev/serial
          type: Directory
      - name: data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-data
      - name: config
        configMap:
          name: zigbee2mqtt-config 